name: app_utils
description: A new Flutter package project.
publish_to: none
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  design_system:
    path: ../design_system
  data:
    path: ../data

  freezed_annotation: ^2.4.4
  freezed: ^2.5.7
  sprintf: ^7.0.0
  intl: ^0.20.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13

  mocktail: ^1.0.1

flutter:

